### ISSUE TITLE
Secret key not saving

### ISSUE THREAD

**Issue by reendisgroup** [sendwheel/tw-receiver#3]
The secret key field keeps blanking out after setting it in the settings and reloading. It is set in the .php but when reloading the html and going into settings it is blank which causes a “missing user credentials” error and the wiki is not saved without re-entering the secret key each time in settings.

**Comment by sendwheel** [comment]
This sounds more like you may have a browser->TWiki issue. The wiki uses (primarily) local-storage on the browser to hold parameters like the secret key and other config settings. Are other configuration parameters saving for you (things like color for example)?

**Comment by reendisgroup** [comment]
You are correct. I had Privacy mode ON in the browser on my iPad and this caused the secret key field to not populate with previously set value. I tested this in Chrome on the iPad too and it gave the same result. Turning off privacy mode and not running in incognito mode in Chrome solved the problem. Thank you.
